### ISSUE TITLE
Phase out VDD configuration

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/d8-quickstart#8]
As part of the install process could the DeesonScriptHandler ask for the 'project name' and then automatically replace 'PROJECT' with that name in the relevant files (e.g. src/settings/settings.php)?

Also could it create the correct drush alias file (drush/sites.aliases.drushrc.php) from the example one?

**Comment by markpdeeson** [comment]
The PROJECT variables are part of the VDD configuration which we should phase out of the project.
